name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      dockerhub_username:
        required: true
      dockerhub_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v4
      
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to the Registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.dockerhub_username}}
          password: ${{secrets.dockerhub_password}}
      
      - name: Set the tag
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi
      
      - name: Build and Push the Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.dockerhub_username}}/${{inputs.image_name}}:${{env.final_tag}}
          
          
  do-something-else:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello"
